In [1]:
import pandas as pd
import numpy as np

In [37]:
concrete_data = pd.read_csv('FuelConsumption.csv')
concrete_data.head()

,MODELYEAR,MAKE,MODEL,VEHICLECLASS,ENGINESIZE,CYLINDERS,TRANSMISSION,FUELTYPE,FUELCONSUMPTION_CITY,FUELCONSUMPTION_HWY,FUELCONSUMPTION_COMB,FUELCONSUMPTION_COMB_MPG,CO2EMISSIONS
0,2014,ACURA,ILX,COMPACT,2.0,4,AS5,Z,9.9,6.7,8.5,33,196
1,2014,ACURA,ILX,COMPACT,2.4,4,M6,Z,11.2,7.7,9.6,29,221
2,2014,ACURA,ILX HYBRID,COMPACT,1.5,4,AV7,Z,6.0,5.8,5.9,48,136
3,2014,ACURA,MDX 4WD,SUV - SMALL,3.5,6,AS6,Z,12.7,9.1,11.1,25,255
4,2014,ACURA,RDX AWD,SUV - SMALL,3.5,6,AS6,Z,12.1,8.7,10.6,27,244

In [38]:
concrete_data.shape

(1067, 13)

In [40]:
concrete_data = concrete_data.describe()

In [41]:
concrete_data.isnull().sum()

MODELYEAR                   0
ENGINESIZE                  0
CYLINDERS                   0
FUELCONSUMPTION_CITY        0
FUELCONSUMPTION_HWY         0
FUELCONSUMPTION_COMB        0
FUELCONSUMPTION_COMB_MPG    0
CO2EMISSIONS                0
dtype: int64

In [42]:
concrete_data_columns = concrete_data.columns
predictors = concrete_data[concrete_data_columns[concrete_data_columns != 'CO2EMISSIONS']]
target = concrete_data['CO2EMISSIONS']

In [43]:
predictors.head()

,MODELYEAR,ENGINESIZE,CYLINDERS,FUELCONSUMPTION_CITY,FUELCONSUMPTION_HWY,FUELCONSUMPTION_COMB,FUELCONSUMPTION_COMB_MPG
count,1067.0,1067.000000,1067.000000,1067.000000,1067.000000,1067.000000,1067.000000
mean,2014.0,3.346298,5.794752,13.296532,9.474602,11.580881,26.441425
std,0.0,1.415895,1.797447,4.101253,2.794510,3.485595,7.468702
min,2014.0,1.000000,3.000000,4.600000,4.900000,4.700000,11.000000
25%,2014.0,2.000000,4.000000,10.250000,7.500000,9.000000,21.000000

In [44]:
target.head()

count    1067.000000
mean      256.228679
std        63.372304
min       108.000000
25%       207.000000
Name: CO2EMISSIONS, dtype: float64

In [45]:
predictors_norm = (predictors - predictors.mean())/predictors.std()
predictors_norm.head()

,MODELYEAR,ENGINESIZE,CYLINDERS,FUELCONSUMPTION_CITY,FUELCONSUMPTION_HWY,FUELCONSUMPTION_COMB,FUELCONSUMPTION_COMB_MPG
count,-0.777145,2.474827,2.474785,2.474289,2.474630,2.474462,2.472561
mean,0.498619,-0.353713,-0.353552,-0.352520,-0.352944,-0.352634,-0.352378
std,-2.214570,-0.358847,-0.364205,-0.377189,-0.370805,-0.374318,-0.403885
min,0.498619,-0.359953,-0.361000,-0.375851,-0.365176,-0.371065,-0.394298
25%,0.498619,-0.357293,-0.358335,-0.360693,-0.358224,-0.359547,-0.367150

In [46]:
import keras
from keras.models import Sequential
from keras.layers import Dense

In [47]:
n_cols = predictors_norm.shape[1]

In [48]:
def regression_model():
    model = Sequential()
    model.add(Dense(50, activation = 'relu', input_shape =(n_cols,) ))
    model.add(Dense(50,activation = 'relu'))
    model.add(Dense(1))

    model.compile(optimizer = 'adam', loss = 'mean_squared_error')
    return model

In [49]:
model = regression_model()
model.fit(predictors_norm, target, validation_split = 0.2, epochs =100, verbose = 2)

Train on 6 samples, validate on 2 samples
Epoch 1/100
 - 0s - loss: 220658.8594 - val_loss: 162053.7812
Epoch 2/100
 - 0s - loss: 220609.9375 - val_loss: 162031.4062
Epoch 3/100
 - 0s - loss: 220553.4844 - val_loss: 162007.3281
Epoch 4/100
 - 0s - loss: 220493.5781 - val_loss: 161981.9688
Epoch 5/100
 - 0s - loss: 220431.8125 - val_loss: 161955.8281
Epoch 6/100
 - 0s - loss: 220368.6250 - val_loss: 161928.9531
Epoch 7/100
 - 0s - loss: 220304.3750 - val_loss: 161901.6406
Epoch 8/100
 - 0s - loss: 220239.5781 - val_loss: 161874.5781
Epoch 9/100
 - 0s - loss: 220173.7500 - val_loss: 161847.6875
Epoch 10/100
 - 0s - loss: 220107.2500 - val_loss: 161820.4688
Epoch 11/100
 - 0s - loss: 220041.4219 - val_loss: 161792.7656
Epoch 12/100
 - 0s - loss: 219974.1719 - val_loss: 161764.2344
Epoch 13/100
 - 0s - loss: 219907.8906 - val_loss: 161734.8750
Epoch 14/100
 - 0s - loss: 219840.2344 - val_loss: 161704.7812
Epoch 15/100
 - 0s - loss: 219771.0000 - val_loss: 161673.7188
Epoch 16/100
 - 0s - loss: 219700.0469 - val_loss: 161641.8594
Epoch 17/100
 - 0s - loss: 219627.7344 - val_loss: 161609.3281
Epoch 18/100
 - 0s - loss: 219555.8750 - val_loss: 161576.2188
Epoch 19/100
 - 0s - loss: 219483.0000 - val_loss: 161542.5781
Epoch 20/100
 - 0s - loss: 219409.0625 - val_loss: 161507.7031
Epoch 21/100
 - 0s - loss: 219333.1250 - val_loss: 161471.9219
Epoch 22/100
 - 0s - loss: 219255.9844 - val_loss: 161435.1719
Epoch 23/100
 - 0s - loss: 219177.2031 - val_loss: 161397.5000
Epoch 24/100
 - 0s - loss: 219096.5469 - val_loss: 161359.8906
Epoch 25/100
 - 0s - loss: 219015.2500 - val_loss: 161322.2500
Epoch 26/100
 - 0s - loss: 218932.9531 - val_loss: 161283.0938
Epoch 27/100
 - 0s - loss: 218847.7344 - val_loss: 161242.8438
Epoch 28/100
 - 0s - loss: 218760.2031 - val_loss: 161201.3906
Epoch 29/100
 - 0s - loss: 218670.3594 - val_loss: 161158.7656
Epoch 30/100
 - 0s - loss: 218578.1406 - val_loss: 161114.7812
Epoch 31/100
 - 0s - loss: 218483.4844 - val_loss: 161069.4688
Epoch 32/100
 - 0s - loss: 218387.3750 - val_loss: 161022.8281
Epoch 33/100
 - 0s - loss: 218290.5469 - val_loss: 160974.8281
Epoch 34/100
 - 0s - loss: 218190.9375 - val_loss: 160925.4219
Epoch 35/100
 - 0s - loss: 218087.4375 - val_loss: 160874.5781
Epoch 36/100
 - 0s - loss: 217978.3906 - val_loss: 160822.2188
Epoch 37/100
 - 0s - loss: 217865.0469 - val_loss: 160768.2969
Epoch 38/100
 - 0s - loss: 217747.7500 - val_loss: 160712.7812
Epoch 39/100
 - 0s - loss: 217627.4219 - val_loss: 160655.6250
Epoch 40/100
 - 0s - loss: 217503.1250 - val_loss: 160596.7500
Epoch 41/100
 - 0s - loss: 217374.8125 - val_loss: 160536.1562
Epoch 42/100
 - 0s - loss: 217242.4531 - val_loss: 160473.7500
Epoch 43/100
 - 0s - loss: 217106.0781 - val_loss: 160409.5000
Epoch 44/100
 - 0s - loss: 216965.5469 - val_loss: 160343.3438
Epoch 45/100
 - 0s - loss: 216820.8281 - val_loss: 160275.2500
Epoch 46/100
 - 0s - loss: 216671.7969 - val_loss: 160205.1719
Epoch 47/100
 - 0s - loss: 216518.3281 - val_loss: 160133.0312
Epoch 48/100
 - 0s - loss: 216360.4375 - val_loss: 160058.7500
Epoch 49/100
 - 0s - loss: 216197.7656 - val_loss: 159982.2969
Epoch 50/100
 - 0s - loss: 216030.4375 - val_loss: 159903.6250
Epoch 51/100
 - 0s - loss: 215858.7500 - val_loss: 159822.6875
Epoch 52/100
 - 0s - loss: 215683.4219 - val_loss: 159740.1250
Epoch 53/100
 - 0s - loss: 215504.4219 - val_loss: 159654.5156
Epoch 54/100
 - 0s - loss: 215313.3125 - val_loss: 159566.4375
Epoch 55/100
 - 0s - loss: 215115.6250 - val_loss: 159475.9219
Epoch 56/100
 - 0s - loss: 214911.5469 - val_loss: 159382.8438
Epoch 57/100
 - 0s - loss: 214701.1250 - val_loss: 159287.1094
Epoch 58/100
 - 0s - loss: 214484.3594 - val_loss: 159189.5000
Epoch 59/100
 - 0s - loss: 214262.9844 - val_loss: 159088.3594
Epoch 60/100
 - 0s - loss: 214033.3750 - val_loss: 158984.3906
Epoch 61/100
 - 0s - loss: 213797.1875 - val_loss: 158877.5469
Epoch 62/100
 - 0s - loss: 213554.3281 - val_loss: 158767.7656
Epoch 63/100
 - 0s - loss: 213304.7500 - val_loss: 158655.8438
Epoch 64/100
 - 0s - loss: 213050.1875 - val_loss: 158539.8906
Epoch 65/100
 - 0s - loss: 212786.6094 - val_loss: 158420.6094
Epoch 66/100
 - 0s - loss: 212515.3281 - val_loss: 158297.9062
Epoch 67/100
 - 0s - loss: 212235.6719 - val_loss: 158171.1250
Epoch 68/100
 - 0s - loss: 211943.2969 - val_loss: 158039.8281
Epoch 69/100
 - 0s - loss: 211640.8125 - val_loss: 157904.4375
Epoch 70/100
 - 0s - loss: 211328.9375 - val_loss: 157764.5156
Epoch 71/100
 - 0s - loss: 211007.8906 - val_loss: 157620.3750
Epoch 72/100
 - 0s - loss: 210677.2656 - val_loss: 157472.0156
Epoch 73/100
 - 0s - loss: 210337.1406 - val_loss: 157319.2031
Epoch 74/100
 - 0s - loss: 209987.4844 - val_loss: 157161.7500
Epoch 75/100
 - 0s - loss: 209628.0469 - val_loss: 156999.8594
Epoch 76/100
 - 0s - loss: 209258.9844 - val_loss: 156834.5312
Epoch 77/100
 - 0s - loss: 208882.5781 - val_loss: 156663.7188
Epoch 78/100
 - 0s - loss: 208494.1250 - val_loss: 156488.3750
Epoch 79/100
 - 0s - loss: 208095.7344 - val_loss: 156308.0000
Epoch 80/100
 - 0s - loss: 207687.5781 - val_loss: 156122.7344
Epoch 81/100
 - 0s - loss: 207270.1406 - val_loss: 155932.2969
Epoch 82/100
 - 0s - loss: 206842.1719 - val_loss: 155737.9219
Epoch 83/100
 - 0s - loss: 206406.3750 - val_loss: 155537.2812
Epoch 84/100
 - 0s - loss: 205957.5781 - val_loss: 155330.6406
Epoch 85/100
 - 0s - loss: 205496.6094 - val_loss: 155119.1094
Epoch 86/100
 - 0s - loss: 205022.1250 - val_loss: 154902.2188
Epoch 87/100
 - 0s - loss: 204535.4219 - val_loss: 154680.0000
Epoch 88/100
 - 0s - loss: 204036.7500 - val_loss: 154452.5156
Epoch 89/100
 - 0s - loss: 203526.1094 - val_loss: 154218.4375
Epoch 90/100
 - 0s - loss: 203003.5000 - val_loss: 153979.0781
Epoch 91/100
 - 0s - loss: 202468.9375 - val_loss: 153734.1562
Epoch 92/100
 - 0s - loss: 201922.3281 - val_loss: 153483.6094
Epoch 93/100
 - 0s - loss: 201363.6406 - val_loss: 153227.3750
Epoch 94/100
 - 0s - loss: 200792.8125 - val_loss: 152965.4062
Epoch 95/100
 - 0s - loss: 200209.6875 - val_loss: 152697.6719
Epoch 96/100
 - 0s - loss: 199614.2656 - val_loss: 152424.0938
Epoch 97/100
 - 0s - loss: 199006.4375 - val_loss: 152144.5625
Epoch 98/100
 - 0s - loss: 198386.0781 - val_loss: 151858.8906
Epoch 99/100
 - 0s - loss: 197753.1875 - val_loss: 151563.9688
Epoch 100/100
 - 0s - loss: 197107.4375 - val_loss: 151259.5000

Accuracy : 185149.9375 %