In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
complaint_df = pd.read_csv('complaints.csv')
complaint_df.head()

,Date received,Product,Sub-product,Issue,Sub-issue,Consumer complaint narrative,Company public response,Company,State,ZIP code,Tags,Consumer consent provided?,Submitted via,Date sent to company,Company response to consumer,Timely response?,Consumer disputed?,Complaint ID
0,2019-09-24,Debt collection,I do not know,Attempts to collect debt not owed,Debt is not yours,transworld systems inc. \nis trying to collect...,NaN,TRANSWORLD SYSTEMS INC,FL,335XX,NaN,Consent provided,Web,2019-09-24,Closed with explanation,Yes,NaN,3384392
1,2019-09-19,"Credit reporting, credit repair services, or o...",Credit reporting,Incorrect information on your report,Information belongs to someone else,NaN,Company has responded to the consumer and the ...,Experian Information Solutions Inc.,PA,15206,NaN,Consent not provided,Web,2019-09-20,Closed with non-monetary relief,Yes,NaN,3379500
2,2019-10-25,"Credit reporting, credit repair services, or o...",Credit reporting,Incorrect information on your report,Information belongs to someone else,I would like to request the suppression of the...,Company has responded to the consumer and the ...,"TRANSUNION INTERMEDIATE HOLDINGS, INC.",CA,937XX,NaN,Consent provided,Web,2019-10-25,Closed with explanation,Yes,NaN,3417821
3,2019-11-08,Debt collection,I do not know,Communication tactics,Frequent or repeated calls,"Over the past 2 weeks, I have been receiving e...",NaN,"Diversified Consultants, Inc.",NC,275XX,NaN,Consent provided,Web,2019-11-08,Closed with explanation,Yes,NaN,3433198
4,2019-02-08,Vehicle loan or lease,Lease,Problem with a credit reporting company's inve...,Their investigation did not fix an error on yo...,NaN,NaN,HYUNDAI CAPITAL AMERICA,FL,33161,NaN,Consent not provided,Web,2019-02-08,Closed with non-monetary relief,Yes,NaN,3146310

In [3]:
complaint_df['Consumer disputed?']=complaint_df["Consumer disputed?"].replace(np.nan, 1)
complaint_df['Consumer disputed?']=np.where(complaint_df['Consumer disputed?']=="Yes",0,1)

In [4]:
complaint_df.head()

,Date received,Product,Sub-product,Issue,Sub-issue,Consumer complaint narrative,Company public response,Company,State,ZIP code,Tags,Consumer consent provided?,Submitted via,Date sent to company,Company response to consumer,Timely response?,Consumer disputed?,Complaint ID
0,2019-09-24,Debt collection,I do not know,Attempts to collect debt not owed,Debt is not yours,transworld systems inc. \nis trying to collect...,NaN,TRANSWORLD SYSTEMS INC,FL,335XX,NaN,Consent provided,Web,2019-09-24,Closed with explanation,Yes,1,3384392
1,2019-09-19,"Credit reporting, credit repair services, or o...",Credit reporting,Incorrect information on your report,Information belongs to someone else,NaN,Company has responded to the consumer and the ...,Experian Information Solutions Inc.,PA,15206,NaN,Consent not provided,Web,2019-09-20,Closed with non-monetary relief,Yes,1,3379500
2,2019-10-25,"Credit reporting, credit repair services, or o...",Credit reporting,Incorrect information on your report,Information belongs to someone else,I would like to request the suppression of the...,Company has responded to the consumer and the ...,"TRANSUNION INTERMEDIATE HOLDINGS, INC.",CA,937XX,NaN,Consent provided,Web,2019-10-25,Closed with explanation,Yes,1,3417821
3,2019-11-08,Debt collection,I do not know,Communication tactics,Frequent or repeated calls,"Over the past 2 weeks, I have been receiving e...",NaN,"Diversified Consultants, Inc.",NC,275XX,NaN,Consent provided,Web,2019-11-08,Closed with explanation,Yes,1,3433198
4,2019-02-08,Vehicle loan or lease,Lease,Problem with a credit reporting company's inve...,Their investigation did not fix an error on yo...,NaN,NaN,HYUNDAI CAPITAL AMERICA,FL,33161,NaN,Consent not provided,Web,2019-02-08,Closed with non-monetary relief,Yes,1,3146310

In [5]:
complaint_df['Date received'] = pd.to_datetime(complaint_df['Date received'])
print(complaint_df['Date received'].dtype)

datetime64[ns]

In [6]:
complaint_df['Year'] = complaint_df['Date received'].dt.year

In [7]:
complaint_df.head()

,Date received,Product,Sub-product,Issue,Sub-issue,Consumer complaint narrative,Company public response,Company,State,ZIP code,Tags,Consumer consent provided?,Submitted via,Date sent to company,Company response to consumer,Timely response?,Consumer disputed?,Complaint ID,Year
0,2019-09-24,Debt collection,I do not know,Attempts to collect debt not owed,Debt is not yours,transworld systems inc. \nis trying to collect...,NaN,TRANSWORLD SYSTEMS INC,FL,335XX,NaN,Consent provided,Web,2019-09-24,Closed with explanation,Yes,1,3384392,2019
1,2019-09-19,"Credit reporting, credit repair services, or o...",Credit reporting,Incorrect information on your report,Information belongs to someone else,NaN,Company has responded to the consumer and the ...,Experian Information Solutions Inc.,PA,15206,NaN,Consent not provided,Web,2019-09-20,Closed with non-monetary relief,Yes,1,3379500,2019
2,2019-10-25,"Credit reporting, credit repair services, or o...",Credit reporting,Incorrect information on your report,Information belongs to someone else,I would like to request the suppression of the...,Company has responded to the consumer and the ...,"TRANSUNION INTERMEDIATE HOLDINGS, INC.",CA,937XX,NaN,Consent provided,Web,2019-10-25,Closed with explanation,Yes,1,3417821,2019
3,2019-11-08,Debt collection,I do not know,Communication tactics,Frequent or repeated calls,"Over the past 2 weeks, I have been receiving e...",NaN,"Diversified Consultants, Inc.",NC,275XX,NaN,Consent provided,Web,2019-11-08,Closed with explanation,Yes,1,3433198,2019
4,2019-02-08,Vehicle loan or lease,Lease,Problem with a credit reporting company's inve...,Their investigation did not fix an error on yo...,NaN,NaN,HYUNDAI CAPITAL AMERICA,FL,33161,NaN,Consent not provided,Web,2019-02-08,Closed with non-monetary relief,Yes,1,3146310,2019

In [8]:
missing_data = complaint_df.isnull()
missing_data.head()

,Date received,Product,Sub-product,Issue,Sub-issue,Consumer complaint narrative,Company public response,Company,State,ZIP code,Tags,Consumer consent provided?,Submitted via,Date sent to company,Company response to consumer,Timely response?,Consumer disputed?,Complaint ID,Year
0,False,False,False,False,False,False,True,False,False,False,True,False,False,False,False,False,False,False,False
1,False,False,False,False,False,True,False,False,False,False,True,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,True,False,False,False,True,False,False,False,False,False,False,False,False
4,False,False,False,False,False,True,True,False,False,False,True,False,False,False,False,False,False,False,False

In [9]:
for col in missing_data.columns.values.tolist():
    print (col)
    print(missing_data[col].value_counts())
    print("")

Date received
False    1645078
Name: Date received, dtype: int64

Product
False    1645078
Name: Product, dtype: int64

Sub-product
False    1409913
True      235165
Name: Sub-product, dtype: int64

Issue
False    1645077
True           1
Name: Issue, dtype: int64

Sub-issue
False    1072376
True      572702
Name: Sub-issue, dtype: int64

Consumer complaint narrative
True     1094037
False     551041
Name: Consumer complaint narrative, dtype: int64

Company public response
True     1001837
False     643241
Name: Company public response, dtype: int64

Company
False    1645078
Name: Company, dtype: int64

State
False    1617131
True       27947
Name: State, dtype: int64

ZIP code
False    1487712
True      157366
Name: ZIP code, dtype: int64

Tags
True     1423015
False     222063
Name: Tags, dtype: int64

Consumer consent provided?
False    1004144
True      640934
Name: Consumer consent provided?, dtype: int64

Submitted via
False    1645078
Name: Submitted via, dtype: int64

Date sent to company
False    1645078
Name: Date sent to company, dtype: int64

Company response to consumer
False    1645077
True           1
Name: Company response to consumer, dtype: int64

Timely response?
False    1645078
Name: Timely response?, dtype: int64

Consumer disputed?
False    1645078
Name: Consumer disputed?, dtype: int64

Complaint ID
False    1645078
Name: Complaint ID, dtype: int64

Year
False    1645078
Name: Year, dtype: int64

In [10]:
complaint_df.dropna(subset=["Product"], axis = 0, inplace=True)
complaint_df.reset_index(drop = True, inplace = True)

In [11]:
complaint_df.head()

,Date received,Product,Sub-product,Issue,Sub-issue,Consumer complaint narrative,Company public response,Company,State,ZIP code,Tags,Consumer consent provided?,Submitted via,Date sent to company,Company response to consumer,Timely response?,Consumer disputed?,Complaint ID,Year
0,2019-09-24,Debt collection,I do not know,Attempts to collect debt not owed,Debt is not yours,transworld systems inc. \nis trying to collect...,NaN,TRANSWORLD SYSTEMS INC,FL,335XX,NaN,Consent provided,Web,2019-09-24,Closed with explanation,Yes,1,3384392,2019
1,2019-09-19,"Credit reporting, credit repair services, or o...",Credit reporting,Incorrect information on your report,Information belongs to someone else,NaN,Company has responded to the consumer and the ...,Experian Information Solutions Inc.,PA,15206,NaN,Consent not provided,Web,2019-09-20,Closed with non-monetary relief,Yes,1,3379500,2019
2,2019-10-25,"Credit reporting, credit repair services, or o...",Credit reporting,Incorrect information on your report,Information belongs to someone else,I would like to request the suppression of the...,Company has responded to the consumer and the ...,"TRANSUNION INTERMEDIATE HOLDINGS, INC.",CA,937XX,NaN,Consent provided,Web,2019-10-25,Closed with explanation,Yes,1,3417821,2019
3,2019-11-08,Debt collection,I do not know,Communication tactics,Frequent or repeated calls,"Over the past 2 weeks, I have been receiving e...",NaN,"Diversified Consultants, Inc.",NC,275XX,NaN,Consent provided,Web,2019-11-08,Closed with explanation,Yes,1,3433198,2019
4,2019-02-08,Vehicle loan or lease,Lease,Problem with a credit reporting company's inve...,Their investigation did not fix an error on yo...,NaN,NaN,HYUNDAI CAPITAL AMERICA,FL,33161,NaN,Consent not provided,Web,2019-02-08,Closed with non-monetary relief,Yes,1,3146310,2019

In [12]:
complaint_df.drop(['Sub-product','Date received', 'Issue', 'Sub-issue','Consumer complaint narrative', 'Company public response', 'State','ZIP code', 'Tags', 'Consumer consent provided?', 'Submitted via', 'Date sent to company', 'Company response to consumer', 'Timely response?', 'Complaint ID'], axis = 1, inplace = True)

In [13]:
complaint_df.head()

,Product,Company,Consumer disputed?,Year
0,Debt collection,TRANSWORLD SYSTEMS INC,1,2019
1,"Credit reporting, credit repair services, or o...",Experian Information Solutions Inc.,1,2019
2,"Credit reporting, credit repair services, or o...","TRANSUNION INTERMEDIATE HOLDINGS, INC.",1,2019
3,Debt collection,"Diversified Consultants, Inc.",1,2019
4,Vehicle loan or lease,HYUNDAI CAPITAL AMERICA,1,2019

In [14]:
complaint_df = complaint_df.sort_values('Product')

In [15]:
complaint_df.head()

,Product,Company,Consumer disputed?,Year
779737,Bank account or service,TD BANK US HOLDING COMPANY,1,2016
1116074,Bank account or service,PNC Bank N.A.,1,2017
1277125,Bank account or service,JPMORGAN CHASE & CO.,1,2015
1374064,Bank account or service,"CITIBANK, N.A.",1,2016
947586,Bank account or service,JPMORGAN CHASE & CO.,1,2014

In [16]:
num = complaint_df.groupby(['Product', 'Year','Company']).agg({'Consumer disputed?': ['sum']})
total = complaint_df.groupby(['Product', 'Year']).agg({'Consumer disputed?': ['sum']})
total.columns = ['total'] 
num.columns = ['Number of complaints']
num = num.reset_index()
total = total.reset_index()
num.head()

,Product,Year,Company,Number of complaints
0,Bank account or service,2012,ACS Education Services,1
1,Bank account or service,2012,ALLY FINANCIAL INC.,89
2,Bank account or service,2012,AMERICAN EXPRESS COMPANY,20
3,Bank account or service,2012,"ARVEST BANK GROUP, INC.",10
4,Bank account or service,2012,ASSOCIATED BANC-CORP,15

In [17]:
total.head()

                   Product  Year  total
0  Bank account or service  2012   9634
1  Bank account or service  2013  10789
2  Bank account or service  2014  11856
3  Bank account or service  2015  13680
4  Bank account or service  2016  18111

In [18]:
complaint = num.groupby(['Product', 'Year']).max()[['Number of complaints']]
complaint.columns = ['Num of Complaints']
complaint = complaint.reset_index()
complaint.head()

                   Product  Year  Num of Complaints
0  Bank account or service  2012               1724
1  Bank account or service  2013               1877
2  Bank account or service  2014               2067
3  Bank account or service  2015               2406
4  Bank account or service  2016               2675

In [19]:
cx_complaint = pd.merge(complaint, total)
cx_complaint

                    Product  Year  Num of Complaints  total
0   Bank account or service  2012               1724   9634
1   Bank account or service  2013               1877  10789
2   Bank account or service  2014               2067  11856
3   Bank account or service  2015               2406  13680
4   Bank account or service  2016               2675  18111
..                      ...   ...                ...    ...
93    Vehicle loan or lease  2020                289   2716
94         Virtual currency  2014                  0      0
95         Virtual currency  2015                  3      3
96         Virtual currency  2016                  3      3
97         Virtual currency  2017                  3      3

[98 rows x 4 columns]

In [20]:
cx_complaint['Percentage'] = np.round((cx_complaint['Num of Complaints']/cx_complaint['total'])*100)
cx_complaint['Percentage']=cx_complaint["Percentage"].replace(np.nan, 0)
cx_complaint

                    Product  Year  Num of Complaints  total  Percentage
0   Bank account or service  2012               1724   9634        18.0
1   Bank account or service  2013               1877  10789        17.0
2   Bank account or service  2014               2067  11856        17.0
3   Bank account or service  2015               2406  13680        18.0
4   Bank account or service  2016               2675  18111        15.0
..                      ...   ...                ...    ...         ...
93    Vehicle loan or lease  2020                289   2716        11.0
94         Virtual currency  2014                  0      0         0.0
95         Virtual currency  2015                  3      3       100.0
96         Virtual currency  2016                  3      3       100.0
97         Virtual currency  2017                  3      3       100.0

[98 rows x 5 columns]

In [21]:
cx_complaint.to_csv('report.csv')
print(cx_complaint)

                    Product  Year  Num of Complaints  total  Percentage
0   Bank account or service  2012               1724   9634        18.0
1   Bank account or service  2013               1877  10789        17.0
2   Bank account or service  2014               2067  11856        17.0
3   Bank account or service  2015               2406  13680        18.0
4   Bank account or service  2016               2675  18111        15.0
..                      ...   ...                ...    ...         ...
93    Vehicle loan or lease  2020                289   2716        11.0
94         Virtual currency  2014                  0      0         0.0
95         Virtual currency  2015                  3      3       100.0
96         Virtual currency  2016                  3      3       100.0
97         Virtual currency  2017                  3      3       100.0

[98 rows x 5 columns]